// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_x8SA9bJT-adNsG2tMn76_cyik1iddhU',
    appId: '1:75012529959:web:185a8007943f4c174bd302',
    messagingSenderId: '75012529959',
    projectId: 'chat-app-3e53e',
    authDomain: 'chat-app-3e53e.firebaseapp.com',
    storageBucket: 'chat-app-3e53e.firebasestorage.app',
    measurementId: 'G-1SKWW17RQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApf794XJ84-wlYC_MrziI1GQq_rxmP6Gc',
    appId: '1:75012529959:android:b9cb5db34894cad34bd302',
    messagingSenderId: '75012529959',
    projectId: 'chat-app-3e53e',
    storageBucket: 'chat-app-3e53e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbNxxcALFTmw-PkgEuD5anJypzu7Oz7U8',
    appId: '1:75012529959:ios:88121cc869e66c094bd302',
    messagingSenderId: '75012529959',
    projectId: 'chat-app-3e53e',
    storageBucket: 'chat-app-3e53e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbNxxcALFTmw-PkgEuD5anJypzu7Oz7U8',
    appId: '1:75012529959:ios:88121cc869e66c094bd302',
    messagingSenderId: '75012529959',
    projectId: 'chat-app-3e53e',
    storageBucket: 'chat-app-3e53e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_x8SA9bJT-adNsG2tMn76_cyik1iddhU',
    appId: '1:75012529959:web:7ddea4cba1bc6bb84bd302',
    messagingSenderId: '75012529959',
    projectId: 'chat-app-3e53e',
    authDomain: 'chat-app-3e53e.firebaseapp.com',
    storageBucket: 'chat-app-3e53e.firebasestorage.app',
    measurementId: 'G-1VDQ3SRYR4',
  );
}
